/**
 * @typedef AssetDetailsEntry
 * @property {number} assetType
 * @property {string} createdAt
 * @property {string} creatorName
 * @property {number} creatorTargetId
 * @property {string} creatorType
 * @property {string | null} description
 * @property {number} favoriteCount
 * @property {string[]} genres
 * @property {number} id
 * @property {number | null} saleCount
 * @property {boolean} isForSale
 * @property {string[]} itemRestrictions
 * @property {string} itemType
 * @property {*} lowestSellerData Extension
 * @property {string} name
 * @property {string | null} offsaleDeadline
 * @property {string} updatedAt Extension
 * @property {number} price Robux Price
 * @property {number} productId
 * @property {number} currency
 * @property {number|null} priceTickets
 */

// generated by ai because im NOT doing allat manually
/**
 * @typedef {Object} AvatarRules
 * @property {('R6' | 'R15')[]} playerAvatarTypes - Supported avatar types.
 * @property {Scales} scales - Scaling configuration for body parts.
 * @property {WearableAssetType[]} wearableAssetTypes - Wearable asset configuration.
 * @property {BodyColor[]} bodyColorsPalette - All available body colors.
 * @property {BodyColor[]} basicBodyColorsPalette - Subset of basic body colors.
 * @property {number} minimumDeltaEBodyColorDifference - Minimum color difference (DeltaE) for valid body color distinction.
 * @property {DefaultClothingAssetLists} defaultClothingAssetLists - Default clothing assets.
 * @property {boolean} bundlesEnabledForUser - If bundles are enabled for the user.
 * @property {boolean} emotesEnabledForUser - If emotes are enabled for the user.
 */

/**
 * @typedef {Object} ScaleRange
 * @property {number} min - Minimum value for the scale.
 * @property {number} max - Maximum value for the scale.
 * @property {number} increment - Increment step for the scale.
 */

/**
 * @typedef {Object} Scales
 * @property {ScaleRange} height
 * @property {ScaleRange} width
 * @property {ScaleRange} head
 * @property {ScaleRange} proportion
 * @property {ScaleRange} bodyType
 */

/**
 * @typedef {Object} WearableAssetType
 * @property {number} maxNumber - Maximum number of this type that can be worn.
 * @property {number} id - Unique asset type ID.
 * @property {string} name - Name of the asset type.
 */

/**
 * @typedef {Object} BodyColor
 * @property {number} brickColorId - Unique BrickColor ID.
 * @property {string} hexColor - Hexadecimal color code.
 * @property {string} name - Human-readable name of the color.
 */

/**
 * @typedef {Object} DefaultClothingAssetLists
 * @property {number[]} defaultShirtAssetIds - List of default shirt asset IDs.
 * @property {number[]} defaultPantAssetIds - List of default pants asset IDs.
 */
