import route from 'ultimate-express'
import { RequestAutoGeneratedPlaceThumbnail } from '../controllers/gameRCC.js'
import authMiddleware from '../middleware/auth.js'

const router = route.Router();
router.post(`/thumbnail`, authMiddleware, RequestAutoGeneratedPlaceThumbnail);

export default router;