<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NetVips" Version="3.2.0" />
      <PackageReference Include="NetVips.Native.linux-x64" Version="8.18.3" />
      <PackageReference Include="NetVips.Native.win-x64" Version="8.18.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Roblox.Rendering.Contracts\Roblox.Rendering.Contracts.csproj" />
      <ProjectReference Include="..\Roblox.Metrics\Roblox.Metrics.csproj" />
    </ItemGroup>

</Project>
