import conf from "../util/config.js";
import request from "../util/request.js";
import enums from "../util/enums.js";
import joi from "joi";
import xml2js from 'xml2js'
import responseUtil from "../util/response.js";
import PlaceTemplate from '../../scripts/Place.json' with { type: 'json' };
const port = enums.GameRCC;

export const RequestAutoGeneratedPlaceThumbnail = async (req, res) => {
    try {
        const schema = joi.object({
            placeId: joi.number().required().integer(),
            jobExpiration: joi.number().max(60).default(20).integer(),
            x: joi.number().required().integer(),
            y: joi.number().required().integer(),
        })
        const { error } = schema.validate(req.body)
        if (error) {
            return responseUtil(res, 'Invalid form', 400, false, { error: error.message })
        }

        var { placeId, jobExpiration, x, y } = req.body
        if (jobExpiration == undefined) { jobExpiration = 20 }
        const assetUrl = `${conf.baseUrl}asset?id=${placeId}`

        const xml = JSON.parse(JSON.stringify(PlaceTemplate));
        xml.Settings.Arguments[0] = assetUrl;
        xml.Settings.Arguments[2] = x;
        xml.Settings.Arguments[3] = y;
        xml.Settings.Arguments[4] = conf.baseUrl;
        xml.Settings.Arguments[6] = conf.baseUrl;

        const response = await request({
            RCC: port,
            XML: xml,
            jobExpiration,
        })
        xml2js.parseString(response.data, (err, jsXmlData) => {
            if (err) {
                return responseUtil(res, 'An internal server error occurred.', 500, false, { data: enums.RenderFailed })
            }
            const xmlData = jsXmlData['SOAP-ENV:Envelope']['SOAP-ENV:Body'][0]['ns1:BatchJobResponse'][0]['ns1:BatchJobResult'][0]['ns1:value'][0];
            return responseUtil(res, 'success', 200, true, { data: xmlData });
        })
    } catch (err) {
        return responseUtil(res, 'An internal server error occurred.', 500, false, { error: err.message })
    }
}