interface AssetDetailsEntry {
    assetType: number;
    createdAt: string;
    creatorName: string;
    creatorTargetId: number;
    creatorType: string;
    description: string | null;
    favoriteCount: number;
    genres: string[];
    id: number;
    saleCount: number | null;
    isForSale: boolean;
    itemRestrictions: string[];
    itemType: string;
    lowestSellerData?: any;
    name: string;
    offsaleDeadline: string | null;
    updatedAt: string;
    price: number | null;
    productId: number;
    currency: number;
    priceTickets: number | null;
}

// generated by ai because im NOT doing allat manually
interface AvatarRules {
    playerAvatarTypes: ('R6' | 'R15')[];
    scales: Scales;
    wearableAssetTypes: WearableAssetType[];
    bodyColorsPalette: BodyColor[];
    basicBodyColorsPalette: BodyColor[];
    minimumDeltaEBodyColorDifference: number;
    defaultClothingAssetLists: DefaultClothingAssetLists;
    bundlesEnabledForUser: boolean;
    emotesEnabledForUser: boolean;
}

interface ScaleRange {
    min: number;
    max: number;
    increment: number;
}

interface Scales {
    height: ScaleRange;
    width: ScaleRange;
    head: ScaleRange;
    proportion: ScaleRange;
    bodyType: ScaleRange;
}

interface WearableAssetType {
    maxNumber: number;
    id: number;
    name: string;
}

interface BodyColor {
    brickColorId: number;
    hexColor: string;
    name: string;
}

interface DefaultClothingAssetLists {
    defaultShirtAssetIds: number[];
    defaultPantAssetIds: number[];
}

interface RecommendedItemEntry {
    item: RecommendedItemInternal;
    creator: RecommendedItemCreator;
    product: RecommendedItemProduct;
}

interface RecommendedItemInternal {
    assetId: number;
    name: string;
    price: number;
    premiumPrice?: number;
    absoluteUrl: string;
}

interface RecommendedItemCreator {
    creatorId: number;
    creatorType: 'User' | 'Group';
    name: string;
    creatorProfileLink: string;
}

interface RecommendedItemProduct {
    id: number;
    priceInRobux?: number;
    priceInTickets?: number;
    isForsale: boolean;
    isPublicDomain: boolean;
    isResellable: boolean;
    isLimited: boolean;
    isLimitedUnique: boolean;
    isRental: boolean;
    bcRequirement: number;
    totalPrivateSales: number;
    offsaleDeadline?: string;
    noPriceText?: string;
    sellerId: number;
    sellerName?: string;
    lowestPrivateSaleUserAssetId?: number;
    isXboxExclusiveItem: boolean;
}

